</$objtype/mkfile

TARG=traffic-demo energy-demo governance-demo integration-demo
OFILES=traffic-demo.$O energy-demo.$O governance-demo.$O integration-demo.$O

<//$objtype/mkone

clean:V:
	rm -f [$OS].out *.[$OS] y.tab.? y.debug y.output $TARG
